Задачи-блок 8
При выпоолнении задач из блока 8, появились следующие вопросы:
1. первая задача работает, но систематически вылетае, и выдает сообщение "2020-11-18 19:49:15.858414+0300 HW8[6220:446070] [TraitCollection] Class CKBrowserSwitcherViewController overrides the -traitCollection getter, which is not supported. If you're trying to override traits, you must use the appropriate API.
Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
2020-11-18 19:49:21.141941+0300 HW8[6220:446070] Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444"
2. Через код смогла реализовать нужный варинат страницы, но мне неудалось расположить лейбл под картинкой с нимаенованием, как только через массив пытаюсь добавить надпись в лейбл, сами лейблы начинают очень сильно перемещаться по экрану.
3. В целом я разобралась с элементом, единственный момент. Во всех статьях и источниках, что я изучала указывают, что экраны при переходе с использованием UISegmentedControl должны содержать единый формат. По заданию, они у нас отличаются, и то ли поэтому то ли по другой причине, при переходе у меня все элеменыт сохраняются на вью. Не смогла придумать как удалять объекты при переходе по сегментам.